module.exports = {
  //本机服务器
  //"BASE_URL": "http://localhost:4000",
  //个人公网域名
  //"BASE_URL":"http://moriarty.free.ngrok.cc/",
  "BASE_URL":"http://130d10f1.ngrok.io",
  // 公司地址
  //"BASE_URL":"http://157.122.116.176:3000/weapp_meeting/",
  "LOGIN": '/login',
  SITE: '/login/site',
  SEARCH: '/search',
  SEARCH_HISTORY: '/search/history',
  SEARCH_ORDERBYME:'/search/orderByMe',
  SEARCH_RELATEDTOME:'/search/relatedToMe',
  SUGGEST_ADD: '/suggest/add',
  ORDER_INITIATE: '/order/initiate',
  ORDER_ADDMORE: '/order/addmore',
  ORDER_LIST: '/order/list',
  ORDER_DETAIL: '/order/detail',
  ORDER_ATTENDANCE: '/order/attendance',
  ORDER_CANCEL: '/order/cancel',
  ORDER_RENEW: '/order/renew',
  ROOM_TREAD: '/room/tread',
  ROOM_COMMON: '/room/common',
  ROOM_OCCUPY: '/room/occupy',
  ROOM_RESERVED: '/room/reserved',
  ROOM_ALLRESERVED:'/room/allReserved',
  MSG_LIST: '/msg/list',
  MSG_FEEDBACK: '/msg/feedback',
  MSG_AVAILABLEID: '/msg/availableid',
  CONTACT_ADDPERSON: '/contact/addperson',
  CONTACT_SAVEPERSON: '/contact/saveperson',
  CONTACT_GETPERSON: '/contact/getperson',
  CONTACT_DELPERSON: '/contact/delperson',
  CONTACT_ADDGROUP: '/contact/addgroup',
  CONTACT_SAVEGROUP: '/contact/savegroup',
  CONTACT_GETGROUPS: '/contact/getgroups',
  CONTACT_DELGROUP: '/contact/delgroup',
  CONTACT_ADDPERSONTOGROUP: '/contact/addpersontogroup',
  CONTACT_GETPERSONBYGROUP: '/contact/getpersonbygroup',
  CONTACT_DELPERSONINGROUP: '/contact/delpersoningroup',
  CONTACT_GETGROUPOFPERSON: '/contact/getgroupsofperson',
  CONTACT_SAVEPERSONINGROUP: '/contact/savepersoningroup',
  CONTACT_SAVEGROUPONPERSON: '/contact/savegrouponperson',
  CONTACT_SEARCHUSER: '/contact/searchuser',
  CONTACT_GETCOMMONPERSON: '/contact/getcommonperson'
}